version: 0.2

env:
  variables:
    TEST: "ThisIsATest"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
